version: "3"

services:
  openfree-sql:
    image: freeopenuniversity/version0:openfree-db-img
    container_name: deploy-openfree-sql
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    expose:
      - "3306"
    ports:
      - 3306:3306
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=root --execute "SHOW DATABASES;"'
      interval: 2s
      timeout: 20s
      retries: 10

  openfree-service:
    image: freeopenuniversity/version0:openfree-service-img
    container_name: deploy-openfree-service
    depends_on:
      - openfree-sql
    ports:
      - 8180:8080
    restart: on-failure
    #command: ["./entrypoint.sh", "openfree-sql:3306", "--", "java", "-jar", "app/app.jar"]
    command: ["./entrypoint.sh", "openfree-sql:3306", "--", "java", "org.springframework.boot.loader.JarLauncher"]
    environment:
      DATABASE_URL: jdbc:mysql://deploy-openfree-sql:3306/test
      DATABASE_USER: root
      DATABASE_PASSWORD: root

  openfree-web:
    image: freeopenuniversity/version0:openfree-web-img
    container_name: deploy-openfree-web
    depends_on:
      - openfree-service
    ports:
      - 3000:80
    restart: on-failure
